#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ Algorithm ############

algorithm_settings:
    #Currently available options DQN, cma_optimizer
    algorithm:  'CMA_optimizer'
    # Decision making agent definition
    agent_by_zone: False # True if using one agent for each zone, and false using a agent for each car

federated_learning_settings:
    aggregation_count: 2 #5 # Amount of aggregation steps for federated learning
    
    # Multipliers to control aggregation
    city_multiplier: 0.15 # Importance of city-wide average
    zone_multiplier: 0.35 # Importance of zone-wide average
    model_multiplier: 0.50 # Importance of model-wide average

