#created by Santiago 19/07/2024
### Configuration file with hyperparemters for CMA-ES agent

############ Hyperparameters ############
cma_parameters:
    population_dimension: 25
    initial_sigma: 0.1
    max_generations: 10 # Amount of training episodes per session
    #submodel inside cma agent
    model_type: 'optimizer'