#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ Algorithm ############

algorithm : DQN # Currently the only option working

############ Environment Settings ############
environment_settings:
    seeds: [1234, 10225566, 555] # Used for reproducibility
    num_of_agents: 25 #25 # Num of cars in simulation
    num_of_chargers: 3 # 3x this amount of chargers will be used (for origin, destination, and midpoint)
    make: 0 # Not currently used
    model: 0 # Not currently used

    # Coordinates of city regions in London
    coords: 
        - [43.02120034946083, -81.28349087468504] # North London
        - [43.004969336049854, -81.18631870502043] # East London
        - [42.95923445066671, -81.26016049362336] # South London
        - [42.98111190139387, -81.30953935839466] # West London
        - [42.9819404397449, -81.2508736429095] # Central London
    
    radius: 20 # Max radius of the circle containing the entire trip
    starting_charge: 6000 # 6kw starting charge
    usage_per_min: 15600 # Average usage per hour of Tesla
    max_charge: 100000 # 100kW

############ HPP Settings ############
hpp_config:
    # Determine if agent or baseline is used
    # fixed_attributes = [0.5, 0.5] # Assign fixed attributes to compare a baseline [Traffic_mult, Distance_mult]
    fixed_attributes: [] # Determine impact ratings through training