#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ Environment Settings ############
environment_settings:
    seeds: [1234, 10225566, 555] # Used for reproducibility
    num_of_agents: 10 # Num of cars in simulation
    num_of_chargers: 2 # 3x this amount of chargers will be used (for origin, destination, and midpoint)

    # Coordinates of city regions in London
    coords: 
        - [43.02120034946083, -81.28349087468504] # North London
        - [43.004969336049854, -81.18631870502043] # East London
        - [42.95923445066671, -81.26016049362336] # South London
        - [42.98111190139387, -81.30953935839466] # West London
        - [42.9819404397449, -81.2508736429095] # Central London
    
    radius: 20 # Max radius of the circle containing the entire trip
    starting_charge: 6000 # 6kw starting charge

    models: ['Tesla Model Y', 'BYD Song', 'Tesla Model 3'] # The 3 most popular EV models
    usage_per_min: [16400, 14100, 15600] # Average usage per hour for each model in Wh/100 km
    max_charge: [170000, 90000, 170000] # in Watts
