#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ HPP Settings ############
eval_config:
    # Determine if agent or baseline is used
    # fixed_attributes = [0.5, 0.5] # Assign fixed attributes to compare a baseline [Traffic_mult, Distance_mult]
    fixed_attributes: [] # Determine impact ratings through training
    verbose: True # Log episode-specific data during training
    display_training_times: False # Display breakdown of how much each step takes