#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ HPP Settings ############
eval_config:
    # Determine if agent or baseline is used
    # fixed_attributes = [0.5, 0.5] # Assign fixed attributes to compare a baseline [Traffic_mult, Distance_mult]
    fixed_attributes: [] # Determine impact ratings through training
    verbose: True # Log episode-specific data during training
    display_training_times: False # Display breakdown of how much each step takes

    train_model: False # Set to false for model evaluation
    save_data: True # Set to true if you want to save simulation results in a csv file
    generate_plots: True # Set to true if you want to generate plots of the simulation environments
    save_aggregate_rewards: False # Set to true if you want to save the rewards across aggregations
    continue_training: False # Set to true if you want the option to continue training after a full training loop completes