#created by Santiago 26/04/2024
### Configuration file with parameters to run MERL

############ HPP Settings ############
hpp_config:
    # Determine if agent or baseline is used
    # fixed_attributes = [0.5, 0.5] # Assign fixed attributes to compare a baseline [Traffic_mult, Distance_mult]
    fixed_attributes: [] # Determine impact ratings through training
    verbose: True