#created by Santiago 26/04/2024
### Configuration file with hyperparemters for the NN

############ Hyperparameters ############
nn_hyperparameters:
    num_episodes: 2 #12 #50 # Amount of training episodes per session
    learning_rate: 0.00001 # Rate of change for model parameters
    epsilon: 1 # Introduce noise during training
    discount_factor: 0.999 # Present value of future rewards
    epsilon_decay: 0.999 # Rate of decrease for training noise
    batch_size: 100 # Amount of experiences to use when training
    buffer_limit: 150 # Max number of experiences to store in a buffer
    max_num_timesteps: 300 # Max amount of minutes per agent episode
    layers: [128, 64, 64] # Neural network hidden layers

